# Generated by Django 6.0.4 on 2026-04-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('score_easy', models.IntegerField(default=0)),
                ('score_normal', models.IntegerField(default=0)),
                ('score_hard', models.IntegerField(default=0)),
            ],
        ),
    ]
